name: Workflow - Rebuild Website

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-website:
    name: Update Website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          ref: "results"
          path: "results"
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build website
        run: |
          cargo run -- results
      - name: Store generated html
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
