name: Workflow - Tests on wasm

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      gitref:
        required: true
        type: string
      branch:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      repository:
        required: true
        type: string
        default: "bevyengine/bevy"
        description: "Bevy repository to use"
      gitref:
        required: true
        type: string
        default: "main"
        description: "Git reference to use"
      branch:
        required: true
        type: string
        description: "Branch name that will be used for the report"

jobs:
  wasm-run:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: "macos-latest"
            browser: "chromium"
            api: "webgpu"
          - runner: "macos-latest"
            browser: "firefox"
            api: "webgpu"
          # Failed to create wgpu surface
          # - runner: "macos-latest"
          #   browser: "webkit"
          #   api: "webgpu"
          # Unable to find a GPU
          # - runner: "ubuntu-latest"
          #   browser: "chromium"
          #   api: "webgpu"
          # Failed to create wgpu surface
          # - runner: "ubuntu-latest"
          #   browser: "firefox"
          #   api: "webgpu"
          # Unable to find a GPU!
          # - runner: "windows-latest"
          #   browser: "chromium"
          #   api: "webgpu"
          # Failed to create wgpu surface
          # - runner: "windows-latest"
          #   browser: "firefox"
          #   api: "webgpu"

          - runner: "ubuntu-latest"
            browser: "firefox"
            api: "webgl2"
          - runner: "ubuntu-latest"
            browser: "chromium"
            api: "webgl2"
          - runner: "macos-latest"
            browser: "chromium"
            api: "webgl2"
          - runner: "macos-latest"
            browser: "webkit"
            api: "webgl2"
          # crash: Too many bindings of type StorageBuffers in Stage ShaderStages(COMPUTE)
          # - runner: "macos-latest"
          #   browser: "firefox"
          #   api: "webgl2"
          # Failed to create wgpu surface
          # - runner: "windows-latest"
          #   browser: "firefox"
          #   api: "webgl2"
          # crash: BindGroupLayout with 'sparse buffer update bind group layout' label is invalid
          # - runner: "windows-latest"
          #   browser: "chromium"
          #   api: "webgl2"
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.gitref }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown

      - name: Install wasm-bindgen
        run: cargo install --force wasm-bindgen-cli

      - name: Setup playwright
        run: |
          cd .github/start-wasm-example
          npm install
          # update playwright to get the latest browsers
          npm install -D @playwright/test@latest
          npx playwright install --with-deps
          cd ../..

      - name: Run examples (windows)
        if: runner.os == 'windows'
        shell: bash
        run: |
          # workaround for xshell not finding npx (not auto adding the .cmd extension)
          sed -i 's/"npx /"npx.cmd /' tools/build-wasm-example/src/main.rs

          # start a webserver
          python3 -m http.server --directory examples/wasm &

          cargo run -p build-wasm-example -- --browsers ${{ matrix.browser }} --api ${{ matrix.api }} --frames 25 --test 2d_shapes testbed_ui bloom_2d atmospheric_fog pbr split_screen

      - name: Run examples (linux)
        if: runner.os == 'linux'
        shell: bash
        run: |
          # start a webserver
          python3 -m http.server --directory examples/wasm &

          xvfb-run cargo run -p build-wasm-example -- --browsers ${{ matrix.browser }} --api ${{ matrix.api }} --frames 25 --test 2d_shapes testbed_ui bloom_2d atmospheric_fog pbr split_screen

      - name: Run examples (macos)
        if: runner.os == 'macos'
        shell: bash
        run: |
          # start a webserver
          python3 -m http.server --directory examples/wasm &

          cargo run -p build-wasm-example -- --browsers ${{ matrix.browser }} --api ${{ matrix.api }} --frames 25 --test 2d_shapes testbed_ui bloom_2d atmospheric_fog pbr split_screen

      - name: Save screenshots
        uses: actions/upload-artifact@v5
        with:
          name: screenshots-wasm-${{ matrix.browser }}-${{ matrix.api }}-${{ runner.os }}
          path: .github/start-wasm-example/screenshot-*.png

      - name: Install Pixel Eagle CLI
        uses: vleue/PixelEagle-cli/install@v0.2.1

      - name: Send to Pixel Eagle
        run: |
          run=`pixeleagle-cli new-run --metadata '{"api":"${{ matrix.api }}", "browser": "${{ matrix.browser }}", "os":"wasm", "gitref": "${{ inputs.gitref }}", "host-os": "${{ runner.os }}", "branch": "${{ inputs.branch }}"}'`

          cd .github/start-wasm-example

          for screenshot in screenshot-*-${{ matrix.browser }}.png; do
            name=$(echo "$screenshot" | sed 's/screenshot-\(.*\)-${{ matrix.browser }}\.png/\1/')
            mv "$screenshot" "$name.png"
          done

          pixeleagle-cli upload-screenshots --clean-name $run *.png

          pixeleagle-cli --format json compare-run $run --same api --same browser --same host-os --filter branch:main --print-details | jq '{project_id: .project_id, from: .from, to: .to}' > ../../pixeleagle-wasm-${{ runner.os }}-${{ matrix.browser }}-${{ matrix.api }}.json
        env:
          PIXEL_EAGLE_TOKEN: ${{ secrets.PIXELEAGLE }}

      - name: Upload Pixel Eagle status
        uses: actions/upload-artifact@v5
        with:
          name: pixeleagle-wasm-${{ runner.os }}-${{ matrix.browser }}-${{ matrix.api }}
          path: pixeleagle-wasm-${{ runner.os }}-${{ matrix.browser }}-${{ matrix.api }}.json
